"""add property coordinates

Revision ID: 0dd8682e051b
Revises: 626071e4df17
Create Date: 2026-08-26 12:07:45.214881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd8682e051b'
down_revision = '626071e4df17'
branch_labels = None
depends_on = None


def upgrade():
    # Add coordinates temporarily as nullable
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('latitude', sa.Float(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('longitude', sa.Float(), nullable=True)
        )

    # Set coordinates for the existing Cedar Court property
    op.execute(
        "UPDATE properties "
        "SET latitude = 0.5036, longitude = 35.2789 "
        "WHERE latitude IS NULL OR longitude IS NULL"
    )

    # Make coordinates required
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column(
            'latitude',
            existing_type=sa.Float(),
            nullable=False
        )
        batch_op.alter_column(
            'longitude',
            existing_type=sa.Float(),
            nullable=False
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
