"""create end of stay table

Revision ID: 626071e4df17
Revises: d98baf31fade
Create Date: 2026-08-26 11:04:45.341857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626071e4df17'
down_revision = 'd98baf31fade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_of_stays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('end_of_stays')
    # ### end Alembic commands ###
