"""add phone to users

Revision ID: 852e314a0cc4
Revises: 461af865b207
Create Date: 2026-09-17 22:40:10.980919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852e314a0cc4'
down_revision = '461af865b207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
