"""add amenities to properties

Revision ID: 8e774c3841fe
Revises: 852e314a0cc4
Create Date: 2026-09-18 07:45:04.236312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e774c3841fe'
down_revision = '852e314a0cc4'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "amenities",
                sa.JSON(),
                nullable=True
            )
        )

    op.execute(
        "UPDATE properties SET amenities = '[]'::json WHERE amenities IS NULL"
    )

    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.alter_column(
            "amenities",
            existing_type=sa.JSON(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
